### ISSUE TITLE
Uncaught TypeError: this.getActiveItem(...).getPath is not a function

### ISSUE THREAD

**Issue by davidlondono** [haklop/touchbar-git#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [touchbar-git](https://github.com/haklop/touchbar-git) package 0.1.1

### Stack Trace

Uncaught TypeError: this.getActiveItem(...).getPath is not a function

```
At /Users/dalon/.atom/packages/touchbar-git/lib/TouchBarGit.js:102

TypeError: this.getActiveItem(...).getPath is not a function
    at TouchBarGit.getActiveItemPath (/packages/touchbar-git/lib/TouchBarGit.js:102:56)
    at TouchBarGit.getRepositoryForActiveItem (/packages/touchbar-git/lib/TouchBarGit.js:106:54)
    at TouchBarGit.update (/packages/touchbar-git/lib/TouchBarGit.js:43:23)
    at repositorySubscriptions.add.repo.onDidChangeStatuses (/packages/touchbar-git/lib/TouchBarGit.js:92:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Task.callback (/Applications/Atom.app/Contents/Resources/app/src/git-repository.js:412:35)
    at /Applications/Atom.app/Contents/Resources/app/src/task.js:61:78
    at /Applications/Atom.app/Contents/Resources/app/src/task.js:122:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task.js:74:40)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-ctags 5.1.0 
build-npm-apm 0.12.0 
busy-signal 1.4.3 
ctags-status 1.3.7 
git-control 0.9.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.5 
linter-ui-touchbar 0.2.0 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-plus 4.29.2 
minimap-selection 4.5.0 
npm-plus 0.4.0 
platformio-ide-terminal 2.5.5 
pristine-ui 1.1.6 
project-manager 3.3.5 
remote-atom 1.3.11 
script 3.15.0 
sync-settings 0.8.2 
touchbar-git 0.1.1 
touchbar-registry 0.3.1 
tree-view-git-status 1.4.0 
```

**Comment by haklop** [comment]
Fix on v0.1.2
